name: eatsalad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  menu_repository:
    path: packages/menu_repository

  font_awesome_flutter: ^11.0.0
  flutter_bloc: ^8.0.1
  google_fonts: ^8.2.1
  flow_builder: ^0.1.0
  firebase_core: ^1.19.1
  equatable: ^2.1.0
  formz: ^0.8.0
  provider: ^6.1.5+1
  bloc: ^8.0.3
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/

