name: menu_repository
description: A Dart package for the thesaurus domain.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  loyverse_api:
    path: ../loyverse_api
  meta: ^1.3.0
