name: menu_repository
description: A Dart package for the eatsalad menu domain.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  loyverse_api:
    path: ../loyverse_api
  meta: ^1.9.0

dev_dependencies:
  lints: ^6.1.0
